### ISSUE TITLE
DTable TODO/Ideas

### ISSUE THREAD

**Issue by krynju** [JuliaParallel/Dagger.jl#273]
Tables.jl interface:
- [ ] DTable as a source
- [ ] DTable constructors utilizing the interface better if possible - check what is possible and what can be improved
- [ ] Schema usage/handling

Table operations:
- [ ] select
- [ ] transform
- [ ] groupby (discrete values or function input for continuous values)
- [ ] combine(groupby...) as in dataframes to reduce per partition for example
- [ ] join (at least leftjoin)
- [ ] indexing and make it work with other ops?
- [ ] shuffle (internal for groupbys and indexing)

Convenience functions:
- [ ] length
- [ ] column names
- [ ] first, last
- [ ] describe
- [ ] partition information
- [ ] row distribution across partitions

Docs:
- [ ] Best practices on partitioning the table
- [ ] OnlineStats examples once this is merged https://github.com/joshday/OnlineStatsBase.jl/pull/26

**Comment by cwiese** [comment]
Just FYI.... we have used JuliaDB (SparseND and IndexedTables) for many many years.   Our biggest issue with using this in a production application is that every combination of columns, filters, aggregate is a new "compile" (due to passing named tuples as arguments).  The first "query" of any combination could be several minutes (and there are 10000's of combinations) .. the next one takes only a few seconds.   We have tried @nonspecialize, data type hiding .. I think DataFrames has it right.  I was hoping there would be a "Distributed DataFrames" in the future.
